files:
  # List of files to monitor
  paths:
    - "/path/to/file1.txt"
    - "/path/to/file2.log"

interval:
  # Time interval (in seconds) for checking file changes
  check_interval: 10

notifications:
  # Enable or disable notifications on file change
  enabled: true

logging:
  # File to store logs of file changes
  log_file: "/path/to/logs/filesentinel.log"
  # Log level: options are "info", "warn", "error", or "debug"
  log_level: "info"

checksum:
  # Choose checksum algorithm for file comparison: "md5", "sha256", or "none"
  algorithm: "sha256"

alerts:
  # Command to run when a file change is detected
  on_change_command: "notify-send 'File changed'"

performance:
  # Maximum number of worker threads for monitoring
  max_threads: 4
