files:
  # List of files to monitor
  paths:
    - "/path/to/file1.txt"
    - "/path/to/file2.log"

interval:
  # Time interval (in seconds) for checking file changes
  check_interval: 10

notifications:
  # Options: "all", "changes", "none"
  level: "all"


logging:
  # File to store logs of file changes
  log_file: "/path/to/logs/filesentinel.log"
  # Log level: options are "info", "warn", "error", or "debug"
  log_level: "info"

checksum:
  # Choose checksum algorithm for file comparison: "md5", "sha256", or "none"
  algorithm: "sha256"